"""initial migration

Revision ID: 5840e66834f6
Revises: None
Create Date: 2015-08-31 08:24:10.461000

"""

# revision identifiers, used by Alembic.
revision = '5840e66834f6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.BOOLEAN(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
